# crisp_gym/config/envs/my_stacking_env.yaml

gripper_mode: "absolute_continuous"

orientation_representation: angle_axis

cartesian_control_param_config: null
joint_control_param_config: null

observations_to_include_to_state:
  - observation.state.cartesian
  - observation.state.gripper
  - observation.state.target

# No extra sensors for the small policy
sensor_configs: []

min_z: 0.04

robot_config:
  robot_type: "franka"
  time_to_home: 2.0
  publish_frequency: 50.0
  home_config:
    - -1.73960110e-02
    - 9.55319758e-02
    - 8.09703053e-04
    - -1.94272034
    - -4.01435784e-03
    - 2.06584183
    - 7.97426445e-01

# IMPORTANT: This points to the new gripper file we will create in Step 2
gripper_config:
  from_yaml: "grippers/gripper_left_stack_v6.yaml"

camera_configs:
  - camera_name: "primary"
    camera_frame: "primary_link"
    resolution: [256, 256]
    # Note: Your friend specifies /right/... for the primary camera.
    # Ensure this matches your actual ROS topic list from earlier.
    camera_color_image_topic: "/right/right_down_third_person_camera/color/image_raw"
    camera_color_info_topic: "/right/right_down_third_person_camera/color/camera_info"
  - camera_name: "wrist"
    camera_frame: "wrist_link"
    resolution: [256, 256]
    camera_color_image_topic: "left_wrist_camera/color/image_rect_raw"
    camera_color_info_topic: "left_wrist_camera/color/camera_info"

control_frequency: 30.0