min_value: 1150
max_value: 2050
joint_state_topic: /left/gripper/dynamixel_motor/joint_states
command_topic: /left/gripper/dynamixel_motor/command
enable_torque_service: /left/gripper/dynamixel_motor/set_torque
# added here:
max_delta: 0.135  # This is the key change from your friend

